# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crypto < Formula
  desc "Cryptocurrency tracker for the command-line."
  homepage "https://github.com/jasonBirchall/crypto"
  version "0.3.9"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jasonBirchall/crypto/releases/download/0.3.9/crypto_0.3.9_darwin_amd64.tar.gz"
    sha256 "a850d66377a2bbcb522caf3170b2bd928d5d8d04791e46aa8f5fd532855d5f23"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jasonBirchall/crypto/releases/download/0.3.9/crypto_0.3.9_darwin_arm64.tar.gz"
    sha256 "a36e29b95d0a5968702e1af259b29be6085e84a425745f4cd23f621dc2ca2a36"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jasonBirchall/crypto/releases/download/0.3.9/crypto_0.3.9_linux_amd64.tar.gz"
    sha256 "9cb5950beb4e9cb269c3607ff7f6c6f9eb6a2db584bd8e76c6c14db5df8d48ed"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jasonBirchall/crypto/releases/download/0.3.9/crypto_0.3.9_linux_armv6.tar.gz"
    sha256 "54d55f588b9ff02d26aa59d9cdf6f6dcebf54a04c0b120dba06199bcb48d68d2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jasonBirchall/crypto/releases/download/0.3.9/crypto_0.3.9_linux_arm64.tar.gz"
    sha256 "a0083f0341050b7e158bb6b9894fc05c2e5fd410c32d2a688832b2af5030573b"
  end

  depends_on "go"

  def install
    bin.install "crypto"
  end
end
